version: '3.6'
networks:
  public:
    external: true
    name: public
  local:
    internal: true
    name: local

volumes:
  logs:

services:
  mysql:
    container_name: ${DOCKER_PROJECT_NAME}-mysql
    build:
      context: .docker
      dockerfile: mysql.Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        VERSION: 8.0
    networks:
      - public
      - local
    ports:
      - 3306
    volumes:
      - .docker/var/lib/mysql:/var/lib/mysql
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_PROJECT_NAME}
      MYSQL_DATABASE: ${DOCKER_PROJECT_NAME}
      MYSQL_USER: ${DOCKER_PROJECT_NAME}
      MYSQL_PASSWORD: ${DOCKER_PROJECT_NAME}
  php-fpm:
    container_name: ${DOCKER_PROJECT_NAME}-php-fpm
    build:
      context: .docker
      dockerfile: php-fpm.Dockerfile
      args:
        VERSION: 7.2-fpm-alpine
    environment:
      TZ: ${TIMEZONE}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
    networks:
      - public
      - local
    depends_on:
      - mysql
    volumes:
      - .:/app
      - logs:/applogs
  nginx:
    container_name: ${DOCKER_PROJECT_NAME}-nginx
    build:
      context: .docker
      dockerfile: nginx.Dockerfile
    environment:
      TZ: ${TIMEZONE}
      NGINX_VERSION: 1.8
    networks:
      - public
      - local
    depends_on:
      - php-fpm
    ports:
      - "8015:80"
      - "44315:443"
    volumes:
      - .:/app
  composer:
    container_name: ${DOCKER_PROJECT_NAME}-composer
    build:
      context: .docker
      dockerfile: composer.Dockerfile
      args:
        VERSION: 1.7
    environment:
      TZ: ${TIMEZONE}
      PW: /app
      COMPOSER_HOME: /tmp
    volumes:
      - .:/app
